[package]
name = "chessrs"
version = "0.1.0"
edition = "2021"
authors = ["Korie Drake Chaney"]
repository = "https://github.com/KorieDrakeChaney/chessrs"
keywords = ["chess"]
readme = "README.md"
description = "A chess library for Rust."
license = "MIT"

[dependencies]
