[package]
name = "w-chess"
version = "0.1.1"
edition = "2021"
authors = ["Korie Drake Chaney"]
repository = "https://github.com/KorieDrakeChaney/w-chess"
keywords = ["chess"]
readme = "README.md"
description = "A chess library for Rust."
license = "MIT"

[dependencies]
